sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.7
  - TOXENV=py27-1.8
  - TOXENV=py27-1.9
  - TOXENV=py27-master
  - TOXENV=py32-1.7
  - TOXENV=py32-1.8
  - TOXENV=py33-1.7
  - TOXENV=py33-1.8
  - TOXENV=py34-1.7
  - TOXENV=py34-1.8
  - TOXENV=py34-1.9
  - TOXENV=py34-master

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-master
  allow_failures:
    - env: TOXENV=py27-master
    - env: TOXENV=py34-master
    - env: TOXENV=py35-master

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls